CREATE DATABASE HFJQ_RACE_INFO;

CREATE USER 'runner_db_user'@'localhost' IDENTIFIED BY 'runner_db_password';

GRANT SELECT, INSERT, UPDATE, DELETE ON HFJQ_RACE_INFO.* TO 'runner_db_user'@'localhost';

USE HFJQ_RACE_INFO;

CREATE TABLE RUNNERS(
    RUNNER_ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    GENDER VARCHAR(1) NOT NULL,
    FINISH_TIME VARCHAR(10),
    PRIMARY KEY (RUNNER_ID)
);